### Site info:
title: hsclub tech blog
tagline: Markdowns about technology, program, bioinfomatics...
author: kalanny
email: kalanny@hotmail.com
description: "markdowns about technology, program, bioinfomatics..." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "blog, python, raspberryPi, technology, programmer, bioinfomatics"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hsclub.vip" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
github_username: kalanny
favicon:     "/images/website_logo.jpg"
aboutme: Hi, this is kalanny. Welcome to my blog. I hope you will enjoy Hua Sheng Club. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/website_logo.jpg" # your photo.

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
        Aboutme: "About Me"
        Archives: "Archives"
        Categories: "Categories"
        Copyright_Notice: "Copyright Notice"
        Recent_Posts: "Recent Posts"
        Tags: "Tags"
        Previous: "Older"
        Next: "Newer"
        PostedInCategories: "Posted in"
        Taggedwith: "and tagged"  
        PostDate: "on "
        Google_search: "Site Search"
    cn:
        Aboutme: "关于我"
        Archives: "存档"
        Categories: "分类目录"    
        Copyright_Notice: "版权声明"
        Recent_Posts: "近期文章"
        Tags: "标签" 
        Previous: "前一页"
        Next: "后一页"
        PostedInCategories: "目录:"   
        Taggedwith: "| 标签:"
        PostDate: "| 发表时间: "
        Google_search: "站内搜索"

### Build settings
### highlighter: pygments rouge
markdown: kramdown
###highlighter: prism
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
